<a href="https://colab.research.google.com/github/fazilooffsaid/week_lab3/blob/main/exercises_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals Exercises

This notebook contains exercises based on the PyTorch Fundamentals tutorial. Each section corresponds to a topic from the original notebook. Complete the exercises by filling in the code cells where indicated.

## 1. Introduction to Tensors

### Exercise 1.1: Create a scalar tensor
Create a scalar tensor with the value 42 and print its value, number of dimensions (ndim), and shape.

In [1]:
import torch

scalar = torch.tensor(42)

print(scalar)
print(scalar.ndim)
print(scalar.shape)


tensor(42)
0
torch.Size([])


### Exercise 1.2: Create a vector tensor
Create a vector tensor with values [1, 2, 3, 4] and print its value, ndim, and shape.

In [2]:
vector = torch.tensor([1, 2, 3, 4])

print(vector)
print(vector.ndim)
print(vector.shape)


tensor([1, 2, 3, 4])
1
torch.Size([4])


### Exercise 1.3: Create a matrix tensor
Create a 2x3 matrix tensor with values [[1, 2, 3], [4, 5, 6]] and print its details.

In [3]:
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])

print(matrix)
print(matrix.ndim)
print(matrix.shape)


tensor([[1, 2, 3],
        [4, 5, 6]])
2
torch.Size([2, 3])


### Exercise 1.4: Create a 3D tensor
Create a tensor of shape (2, 2, 2) with sequential values from 1 to 8 using torch.arange and reshape.

In [4]:
tensor_3d = torch.arange(1, 9).reshape(2, 2, 2)

print(tensor_3d)
print(tensor_3d.ndim)
print(tensor_3d.shape)


tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
3
torch.Size([2, 2, 2])


## 2. Random Tensors

### Exercise 2.1: Create a random tensor
Create a random tensor of shape (4, 4) and print it along with its dtype.

In [5]:
random_tensor = torch.rand(4, 4)

print(random_tensor)
print(random_tensor.dtype)


tensor([[0.1506, 0.6084, 0.2989, 0.5471],
        [0.5794, 0.8457, 0.0598, 0.9127],
        [0.0688, 0.6235, 0.1500, 0.4920],
        [0.2032, 0.7518, 0.1565, 0.7044]])
torch.float32


### Exercise 2.2: Create an image-sized random tensor
Create a random tensor of shape (3, 224, 224) simulating an image (channels, height, width).

In [6]:
image_tensor = torch.rand(3, 224, 224)

print(image_tensor.shape)


torch.Size([3, 224, 224])


## 3. Zeros and Ones

### Exercise 3.1: Create a tensor of zeros
Create a tensor of zeros with shape (5, 5).

In [7]:
zeros = torch.zeros(5, 5)

print(zeros)


tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


### Exercise 3.2: Create a tensor of ones like another tensor
Create a random tensor of shape (3, 3), then create a tensor of ones with the same shape using ones_like.

In [ ]:
ones_like = torch.ones_like(random_tensor)

print(ones_like)


## 4. Creating Ranges

### Exercise 4.1: Create a range tensor
Create a tensor with values from 0 to 20 with a step of 2 using torch.arange.

In [ ]:
range_tensor = torch.arange(0, 21, 2)

print(range_tensor)


## 5. Tensor Datatypes

### Exercise 5.1: Create tensors with specific dtypes
Create a tensor with values [1.0, 2.0, 3.0] using dtype=torch.float16 and another with dtype=torch.int64.

In [ ]:
float16_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)
int64_tensor = torch.tensor([1, 2, 3], dtype=torch.int64)

print(float16_tensor)
print(int64_tensor)


### Exercise 5.2: Change dtype
Convert the float16_tensor to float32.

In [ ]:
float32_tensor = float16_tensor.to(torch.float32)

print(float32_tensor)
print(float32_tensor.dtype)


## 6. Getting Information from Tensors

### Exercise 6.1: Print tensor info
Create a random tensor of shape (2, 3, 4) and print its shape, dtype, and device.

In [ ]:
info_tensor = torch.rand(2, 3, 4)

print(info_tensor.shape)
print(info_tensor.dtype)
print(info_tensor.device)


## 7. Manipulating Tensors (Basic Operations)

### Exercise 7.1: Perform basic operations
Create a tensor [10, 20, 30]. Add 5, subtract 10, multiply by 2, and divide by 10.

In [9]:
import torch

tensor = torch.tensor([10, 20, 30])

tensor_add = tensor + 5
tensor_sub = tensor_add - 10
tensor_mul = tensor_sub * 2
tensor_div = tensor_mul / 10

print(tensor_div)


tensor([1., 3., 5.])


### Exercise 7.2: Matrix multiplication
Create two tensors A (2x3) and B (3x2) with random values and perform matrix multiplication.

In [ ]:
import torch

A = torch.rand(2, 3)
B = torch.rand(3, 2)

result_mm = torch.mm(A, B)
result_at = A @ B

print(result_mm)
print(result_at)


## 8. Tensor Aggregation

### Exercise 8.1: Find min, max, mean, sum
Create a tensor with values from 0 to 100 and find its min, max, mean, and sum.

In [31]:
min_val = agg_tensor.min()
max_val = agg_tensor.max()
mean_val = agg_tensor.float().mean()
sum_val = agg_tensor.sum()

print("Min:", min_val)
print("Max:", max_val)
print("Mean:", mean_val)
print("Sum:", sum_val)


Min: tensor(0)
Max: tensor(100)
Mean: tensor(50.)
Sum: tensor(5050)


### Exercise 8.2: Argmin and argmax
Find the positions of the minimum and maximum values in the above tensor.

In [13]:
import torch

agg_tensor = torch.arange(0, 101)

argmin_val = agg_tensor.argmin()
argmax_val = agg_tensor.argmax()

print("Argmin index:", argmin_val.item())
print("Argmax index:", argmax_val.item())


Argmin index: 0
Argmax index: 100


## 9. Reshaping, Stacking, Squeezing, Unsqueezing

### Exercise 9.1: Reshape a tensor
Create a tensor of shape (10,) and reshape it to (2, 5).

In [30]:
import torch

reshape_tensor = torch.arange(10)
reshaped = reshape_tensor.reshape(2, 5)

print(reshaped)


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


### Exercise 9.2: Stack tensors
Create two tensors of shape (2, 2) and stack them vertically and horizontally.

In [27]:
import torch

tensor1 = torch.rand(2, 2)
tensor2 = torch.rand(2, 2)

stack_vert = torch.vstack([tensor1, tensor2])
stack_horz = torch.hstack([tensor1, tensor2])

print("Vertical stack:\n", stack_vert)
print("Horizontal stack:\n", stack_horz)


Vertical stack:
 tensor([[0.3860, 0.8964],
        [0.4303, 0.3279],
        [0.4430, 0.7246],
        [0.5230, 0.1795]])
Horizontal stack:
 tensor([[0.3860, 0.8964, 0.4430, 0.7246],
        [0.4303, 0.3279, 0.5230, 0.1795]])


### Exercise 9.3: Squeeze and unsqueeze
Create a tensor of shape (1, 3, 1), squeeze it, then unsqueeze it back on dim=0.

In [19]:
import torch

squeeze_tensor = torch.rand(1, 3, 1)
squeezed = squeeze_tensor.squeeze()
unsqueezed = squeezed.unsqueeze(0)

print("Squeezed shape:", squeezed.shape)
print("Unsqueezed shape:", unsqueezed.shape)


Squeezed shape: torch.Size([3])
Unsqueezed shape: torch.Size([1, 3])


### Exercise 9.4: Permute
Create an image tensor (3, 100, 100) and permute it to (100, 100, 3).

In [ ]:
permuted = image_tensor.permute(1, 2, 0)

print(permuted.shape)


## 10. Indexing

### Exercise 10.1: Index into a tensor
Create a tensor [[[1,2,3],[4,5,6],[7,8,9]]] and index to get 5, then the entire second row.

In [21]:
import torch

index_tensor = torch.tensor([[[1, 2, 3],
                              [4, 5, 6],
                              [7, 8, 9]]])

value_5 = index_tensor[0, 1, 1]
second_row = index_tensor[0, 1, :]

print("Value 5:", value_5)
print("Second row:", second_row)


Value 5: tensor(5)
Second row: tensor([4, 5, 6])


## 11. PyTorch and NumPy

### Exercise 11.1: NumPy to PyTorch
Create a NumPy array [1,2,3,4] and convert it to a PyTorch tensor.

In [25]:
import torch
import numpy as np

numpy_array = np.array([1, 2, 3, 4])
from_numpy = torch.from_numpy(numpy_array)

print(from_numpy)


tensor([1, 2, 3, 4])


### Exercise 11.2: PyTorch to NumPy
Create a PyTorch tensor [5,6,7,8] and convert it to a NumPy array.

In [23]:
import torch

pytorch_tensor = torch.tensor([5, 6, 7, 8])
to_numpy = pytorch_tensor.numpy()

print(to_numpy)


[5 6 7 8]


## 12. Reproducibility

### Exercise 12.1: Set manual seed
Set the manual seed to 77 and create two random tensors of shape (2,2). Check if they are equal.

In [ ]:
torch.manual_seed(77)
rand1 = torch.rand(2, 2)

torch.manual_seed(77)
rand2 = torch.rand(2, 2)

print(rand1 == rand2)


## 13. Running on GPUs

### Exercise 13.1: Check for GPU
Write code to check if CUDA is available and set the device accordingly.

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"

print(device)


### Exercise 13.2: Move tensor to GPU
Create a tensor and move it to the GPU if available. Then move it back to CPU and convert to NumPy.

In [11]:
import torch

gpu_tensor = torch.tensor([10, 20, 30])

device = "cuda" if torch.cuda.is_available() else "cpu"

gpu_tensor = gpu_tensor.to(device)
cpu_numpy = gpu_tensor.cpu().numpy()

print("Tensor on device:", gpu_tensor)
print("Back to CPU NumPy array:", cpu_numpy)


Tensor on device: tensor([10, 20, 30])
Back to CPU NumPy array: [10 20 30]
